#!/usr/bin/env ruby

$:.unshift(File.dirname(__FILE__) + '/lib') unless $LOAD_PATH.include?(File.dirname(__FILE__) + '/lib')

require 'pry'
require 'bot'

Botz::Bot.configure do |b|

  b.base_uri b.api_endpoint

  b.player_key = "ae3a9fdf-2248-4a48-8aac-49c47fcf849a"

end

Botz::Bot.play do
  #move = Logic.execute game_state

  move = { action_name: 'bet', amount: 100, cards: nil }

  make_play move
end


