#!/usr/bin/env ruby

$:.unshift(File.dirname(__FILE__) + '/lib') unless $LOAD_PATH.include?(File.dirname(__FILE__) + '/lib')

require 'pry'
require 'bot'
require 'logic'

Botz::Bot.configure do |b|

  b.base_uri b.api_endpoint

  b.player_key = "54520cdb-9966-48fa-98c0-6829cd873bd8"

end

Botz::Bot.play do
  move = Logic.execute game_state

  make_play move
end


